#pragma once

// Simplified version of vec.pb.h for migration
// In the original AutoDrive project, this would be generated by protobuf

namespace geom {

class Vec2dProto {
public:
    void set_x(double x) { x_ = x; }
    void set_y(double y) { y_ = y; }
    double x() const { return x_; }
    double y() const { return y_; }
    
private:
    double x_ = 0.0;
    double y_ = 0.0;
};

}  // namespace geom